org: mghermanmancarella
service: backend-jobly
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-west-1
  memorySize: 128
functions:
  app:
    handler: app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
plugins:
  - serverless-offline
  - serverless-dotenv-plugin
